services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MILOSshop
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
